FROM python:3.9.10-buster

WORKDIR /usr/local/airflow

COPY requirements.txt .
COPY airflow.cfg .
COPY entrypoint.sh .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

ENV PYTHONPATH "${PYTHONPATH}:/usr/local/airflow/modules"
ENV AIRFLOW_HOME "/usr/local/airflow"

ENV EXECUTOR "Local"

CMD [ "./entrypoint.sh" ]

# Add Custom Configuration